name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++]
        cpp-version: [14, 17, 20]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build unit tests
      run: cd cpp && make
      env:
        CXX: ${{ matrix.compiler }}
        CXX_STANDARD: ${{ matrix.cpp-version }}
    - name: Run unit tests
      run: cd cpp && make test
